In [1]:
pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.0.124-py3-none-any.whl (612 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.6/612.6 kB 15.3 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (3.7.1)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (4.7.0.72)
Requirement already satisfied: Pillow>=7.1.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (8.4.0)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (6.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (2.27.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torch>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (2.0.1+cu118)
Requirement already satisfied: torchvision>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (0.15.2+cu118)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (4.65.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (1.5.3)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (0.12.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (4.40.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics) (2022.7.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (3.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (3.12.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (4.6.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.7.0->ultralytics) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.7.0->ultralytics) (16.0.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->ultralytics) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.7.0->ultralytics) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.7.0->ultralytics) (1.3.0)
Installing collected packages: ultralytics
Successfully installed ultralytics-8.0.124

In [206]:
from ultralytics import YOLO

model = YOLO("last.pt")
results = model.track(source="IMG_5357.mov", show=True, tracker="bytetrack.yaml", save=True, conf=0.5)

WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()



    WARNING ⚠️ stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Usage:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/516) /content/IMG_5357.mov: 640x384 1 ladybug, 375.2ms
video 1/1 (2/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.7ms
video 1/1 (3/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.9ms
video 1/1 (4/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.1ms
video 1/1 (5/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.2ms
video 1/1 (6/516) /content/IMG_5357.mov: 640x384 1 ladybug, 362.7ms
video 1/1 (7/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.5ms
video 1/1 (8/516) /content/IMG_5357.mov: 640x384 1 ladybug, 363.3ms
video 1/1 (9/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.5ms
video 1/1 (10/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.2ms
video 1/1 (11/516) /content/IMG_5357.mov: 640x384 1 ladybug, 368.6ms
video 1/1 (12/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.8ms
video 1/1 (13/516) /content/IMG_5357.mov: 640x384 1 ladybug, 365.1ms
video 1/1 (14/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.5ms
video 1/1 (15/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.6ms
video 1/1 (16/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.9ms
video 1/1 (17/516) /content/IMG_5357.mov: 640x384 1 ladybug, 531.4ms
video 1/1 (18/516) /content/IMG_5357.mov: 640x384 1 ladybug, 613.3ms
video 1/1 (19/516) /content/IMG_5357.mov: 640x384 1 ladybug, 580.7ms
video 1/1 (20/516) /content/IMG_5357.mov: 640x384 1 ladybug, 606.1ms
video 1/1 (21/516) /content/IMG_5357.mov: 640x384 1 ladybug, 569.1ms
video 1/1 (22/516) /content/IMG_5357.mov: 640x384 1 ladybug, 549.9ms
video 1/1 (23/516) /content/IMG_5357.mov: 640x384 1 ladybug, 553.3ms
video 1/1 (24/516) /content/IMG_5357.mov: 640x384 1 ladybug, 363.2ms
video 1/1 (25/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.5ms
video 1/1 (26/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.7ms
video 1/1 (27/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.1ms
video 1/1 (28/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.9ms
video 1/1 (29/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.4ms
video 1/1 (30/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.6ms
video 1/1 (31/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.9ms
video 1/1 (32/516) /content/IMG_5357.mov: 640x384 1 ladybug, 366.1ms
video 1/1 (33/516) /content/IMG_5357.mov: 640x384 1 ladybug, 342.9ms
video 1/1 (34/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.7ms
video 1/1 (35/516) /content/IMG_5357.mov: 640x384 1 ladybug, 357.6ms
video 1/1 (36/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.1ms
video 1/1 (37/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.1ms
video 1/1 (38/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.9ms
video 1/1 (39/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.3ms
video 1/1 (40/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.6ms
video 1/1 (41/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.0ms
video 1/1 (42/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.9ms
video 1/1 (43/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.8ms
video 1/1 (44/516) /content/IMG_5357.mov: 640x384 1 ladybug, 375.4ms
video 1/1 (45/516) /content/IMG_5357.mov: 640x384 1 ladybug, 362.1ms
video 1/1 (46/516) /content/IMG_5357.mov: 640x384 1 ladybug, 373.4ms
video 1/1 (47/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.8ms
video 1/1 (48/516) /content/IMG_5357.mov: 640x384 1 ladybug, 356.9ms
video 1/1 (49/516) /content/IMG_5357.mov: 640x384 1 ladybug, 374.2ms
video 1/1 (50/516) /content/IMG_5357.mov: 640x384 1 ladybug, 368.3ms
video 1/1 (51/516) /content/IMG_5357.mov: 640x384 1 ladybug, 585.1ms
video 1/1 (52/516) /content/IMG_5357.mov: 640x384 1 ladybug, 586.8ms
video 1/1 (53/516) /content/IMG_5357.mov: 640x384 1 ladybug, 565.4ms
video 1/1 (54/516) /content/IMG_5357.mov: 640x384 1 ladybug, 585.5ms
video 1/1 (55/516) /content/IMG_5357.mov: 640x384 1 ladybug, 556.0ms
video 1/1 (56/516) /content/IMG_5357.mov: 640x384 1 ladybug, 553.9ms
video 1/1 (57/516) /content/IMG_5357.mov: 640x384 1 ladybug, 503.4ms
video 1/1 (58/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.1ms
video 1/1 (59/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.4ms
video 1/1 (60/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.0ms
video 1/1 (61/516) /content/IMG_5357.mov: 640x384 1 ladybug, 357.3ms
video 1/1 (62/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.4ms
video 1/1 (63/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.6ms
video 1/1 (64/516) /content/IMG_5357.mov: 640x384 1 ladybug, 357.0ms
video 1/1 (65/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.7ms
video 1/1 (66/516) /content/IMG_5357.mov: 640x384 1 ladybug, 362.1ms
video 1/1 (67/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.3ms
video 1/1 (68/516) /content/IMG_5357.mov: 640x384 1 ladybug, 356.0ms
video 1/1 (69/516) /content/IMG_5357.mov: 640x384 1 ladybug, 362.8ms
video 1/1 (70/516) /content/IMG_5357.mov: 640x384 1 ladybug, 374.7ms
video 1/1 (71/516) /content/IMG_5357.mov: 640x384 1 ladybug, 371.9ms
video 1/1 (72/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.4ms
video 1/1 (73/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.6ms
video 1/1 (74/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.8ms
video 1/1 (75/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.6ms
video 1/1 (76/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.5ms
video 1/1 (77/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.7ms
video 1/1 (78/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.3ms
video 1/1 (79/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.6ms
video 1/1 (80/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.2ms
video 1/1 (81/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.6ms
video 1/1 (82/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.8ms
video 1/1 (83/516) /content/IMG_5357.mov: 640x384 1 ladybug, 367.7ms
video 1/1 (84/516) /content/IMG_5357.mov: 640x384 1 ladybug, 387.9ms
video 1/1 (85/516) /content/IMG_5357.mov: 640x384 1 ladybug, 587.1ms
video 1/1 (86/516) /content/IMG_5357.mov: 640x384 1 ladybug, 568.7ms
video 1/1 (87/516) /content/IMG_5357.mov: 640x384 1 ladybug, 569.2ms
video 1/1 (88/516) /content/IMG_5357.mov: 640x384 1 ladybug, 566.0ms
video 1/1 (89/516) /content/IMG_5357.mov: 640x384 1 ladybug, 551.8ms
video 1/1 (90/516) /content/IMG_5357.mov: 640x384 1 ladybug, 538.6ms
video 1/1 (91/516) /content/IMG_5357.mov: 640x384 1 ladybug, 481.1ms
video 1/1 (92/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.1ms
video 1/1 (93/516) /content/IMG_5357.mov: 640x384 1 ladybug, 356.4ms
video 1/1 (94/516) /content/IMG_5357.mov: 640x384 1 ladybug, 365.7ms
video 1/1 (95/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.9ms
video 1/1 (96/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.7ms
video 1/1 (97/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.2ms
video 1/1 (98/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.6ms
video 1/1 (99/516) /content/IMG_5357.mov: 640x384 1 ladybug, 355.3ms
video 1/1 (100/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.2ms
video 1/1 (101/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.7ms
video 1/1 (102/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.1ms
video 1/1 (103/516) /content/IMG_5357.mov: 640x384 1 ladybug, 355.4ms
video 1/1 (104/516) /content/IMG_5357.mov: 640x384 1 ladybug, 355.5ms
video 1/1 (105/516) /content/IMG_5357.mov: 640x384 1 ladybug, 369.0ms
video 1/1 (106/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.9ms
video 1/1 (107/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.1ms
video 1/1 (108/516) /content/IMG_5357.mov: 640x384 1 ladybug, 356.7ms
video 1/1 (109/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.0ms
video 1/1 (110/516) /content/IMG_5357.mov: 640x384 1 ladybug, 357.5ms
video 1/1 (111/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.2ms
video 1/1 (112/516) /content/IMG_5357.mov: 640x384 1 ladybug, 342.5ms
video 1/1 (113/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.8ms
video 1/1 (114/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.8ms
video 1/1 (115/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.7ms
video 1/1 (116/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.5ms
video 1/1 (117/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.6ms
video 1/1 (118/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.8ms
video 1/1 (119/516) /content/IMG_5357.mov: 640x384 1 ladybug, 575.2ms
video 1/1 (120/516) /content/IMG_5357.mov: 640x384 1 ladybug, 591.2ms
video 1/1 (121/516) /content/IMG_5357.mov: 640x384 1 ladybug, 570.4ms
video 1/1 (122/516) /content/IMG_5357.mov: 640x384 1 ladybug, 568.1ms
video 1/1 (123/516) /content/IMG_5357.mov: 640x384 1 ladybug, 553.9ms
video 1/1 (124/516) /content/IMG_5357.mov: 640x384 1 ladybug, 569.6ms
video 1/1 (125/516) /content/IMG_5357.mov: 640x384 1 ladybug, 486.1ms
video 1/1 (126/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.2ms
video 1/1 (127/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.9ms
video 1/1 (128/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.3ms
video 1/1 (129/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.5ms
video 1/1 (130/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.5ms
video 1/1 (131/516) /content/IMG_5357.mov: 640x384 1 ladybug, 361.3ms
video 1/1 (132/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.3ms
video 1/1 (133/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.3ms
video 1/1 (134/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.1ms
video 1/1 (135/516) /content/IMG_5357.mov: 640x384 1 ladybug, 339.5ms
video 1/1 (136/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.2ms
video 1/1 (137/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.4ms
video 1/1 (138/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.5ms
video 1/1 (139/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.1ms
video 1/1 (140/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.5ms
video 1/1 (141/516) /content/IMG_5357.mov: 640x384 1 ladybug, 339.9ms
video 1/1 (142/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.0ms
video 1/1 (143/516) /content/IMG_5357.mov: 640x384 (no detections), 356.2ms
video 1/1 (144/516) /content/IMG_5357.mov: 640x384 (no detections), 347.5ms
video 1/1 (145/516) /content/IMG_5357.mov: 640x384 (no detections), 362.4ms
video 1/1 (146/516) /content/IMG_5357.mov: 640x384 (no detections), 340.5ms
video 1/1 (147/516) /content/IMG_5357.mov: 640x384 (no detections), 341.5ms
video 1/1 (148/516) /content/IMG_5357.mov: 640x384 (no detections), 356.7ms
video 1/1 (149/516) /content/IMG_5357.mov: 640x384 (no detections), 337.0ms
video 1/1 (150/516) /content/IMG_5357.mov: 640x384 (no detections), 344.8ms
video 1/1 (151/516) /content/IMG_5357.mov: 640x384 (no detections), 355.3ms
video 1/1 (152/516) /content/IMG_5357.mov: 640x384 (no detections), 345.7ms
video 1/1 (153/516) /content/IMG_5357.mov: 640x384 (no detections), 541.5ms
video 1/1 (154/516) /content/IMG_5357.mov: 640x384 (no detections), 586.0ms
video 1/1 (155/516) /content/IMG_5357.mov: 640x384 1 ladybug, 590.3ms
video 1/1 (156/516) /content/IMG_5357.mov: 640x384 1 ladybug, 580.8ms
video 1/1 (157/516) /content/IMG_5357.mov: 640x384 1 ladybug, 551.7ms
video 1/1 (158/516) /content/IMG_5357.mov: 640x384 1 ladybug, 545.6ms
video 1/1 (159/516) /content/IMG_5357.mov: 640x384 1 ladybug, 531.4ms
video 1/1 (160/516) /content/IMG_5357.mov: 640x384 (no detections), 350.4ms
video 1/1 (161/516) /content/IMG_5357.mov: 640x384 (no detections), 357.1ms
video 1/1 (162/516) /content/IMG_5357.mov: 640x384 (no detections), 356.3ms
video 1/1 (163/516) /content/IMG_5357.mov: 640x384 (no detections), 344.8ms
video 1/1 (164/516) /content/IMG_5357.mov: 640x384 (no detections), 368.9ms
video 1/1 (165/516) /content/IMG_5357.mov: 640x384 (no detections), 361.1ms
video 1/1 (166/516) /content/IMG_5357.mov: 640x384 (no detections), 352.1ms
video 1/1 (167/516) /content/IMG_5357.mov: 640x384 (no detections), 365.6ms
video 1/1 (168/516) /content/IMG_5357.mov: 640x384 (no detections), 354.8ms
video 1/1 (169/516) /content/IMG_5357.mov: 640x384 (no detections), 347.0ms
video 1/1 (170/516) /content/IMG_5357.mov: 640x384 (no detections), 348.8ms
video 1/1 (171/516) /content/IMG_5357.mov: 640x384 (no detections), 343.9ms
video 1/1 (172/516) /content/IMG_5357.mov: 640x384 (no detections), 344.3ms
video 1/1 (173/516) /content/IMG_5357.mov: 640x384 1 ladybug, 556.1ms
video 1/1 (174/516) /content/IMG_5357.mov: 640x384 (no detections), 343.2ms
video 1/1 (175/516) /content/IMG_5357.mov: 640x384 (no detections), 357.1ms
video 1/1 (176/516) /content/IMG_5357.mov: 640x384 (no detections), 356.0ms
video 1/1 (177/516) /content/IMG_5357.mov: 640x384 (no detections), 345.2ms
video 1/1 (178/516) /content/IMG_5357.mov: 640x384 (no detections), 356.5ms
video 1/1 (179/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.8ms
video 1/1 (180/516) /content/IMG_5357.mov: 640x384 1 ladybug, 369.9ms
video 1/1 (181/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.1ms
video 1/1 (182/516) /content/IMG_5357.mov: 640x384 (no detections), 354.8ms
video 1/1 (183/516) /content/IMG_5357.mov: 640x384 1 ladybug, 351.8ms
video 1/1 (184/516) /content/IMG_5357.mov: 640x384 (no detections), 349.0ms
video 1/1 (185/516) /content/IMG_5357.mov: 640x384 (no detections), 347.3ms
video 1/1 (186/516) /content/IMG_5357.mov: 640x384 (no detections), 383.9ms
video 1/1 (187/516) /content/IMG_5357.mov: 640x384 (no detections), 558.3ms
video 1/1 (188/516) /content/IMG_5357.mov: 640x384 (no detections), 581.8ms
video 1/1 (189/516) /content/IMG_5357.mov: 640x384 (no detections), 593.9ms
video 1/1 (190/516) /content/IMG_5357.mov: 640x384 (no detections), 590.3ms
video 1/1 (191/516) /content/IMG_5357.mov: 640x384 (no detections), 552.5ms
video 1/1 (192/516) /content/IMG_5357.mov: 640x384 (no detections), 551.4ms
video 1/1 (193/516) /content/IMG_5357.mov: 640x384 (no detections), 499.2ms
video 1/1 (194/516) /content/IMG_5357.mov: 640x384 (no detections), 352.5ms
video 1/1 (195/516) /content/IMG_5357.mov: 640x384 1 ladybug, 342.4ms
video 1/1 (196/516) /content/IMG_5357.mov: 640x384 (no detections), 359.4ms
video 1/1 (197/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.9ms
video 1/1 (198/516) /content/IMG_5357.mov: 640x384 (no detections), 345.0ms
video 1/1 (199/516) /content/IMG_5357.mov: 640x384 1 ladybug, 352.9ms
video 1/1 (200/516) /content/IMG_5357.mov: 640x384 1 ladybug, 352.7ms
video 1/1 (201/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.5ms
video 1/1 (202/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.6ms
video 1/1 (203/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.2ms
video 1/1 (204/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.6ms
video 1/1 (205/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.5ms
video 1/1 (206/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.0ms
video 1/1 (207/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.2ms
video 1/1 (208/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.3ms
video 1/1 (209/516) /content/IMG_5357.mov: 640x384 1 ladybug, 339.4ms
video 1/1 (210/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.7ms
video 1/1 (211/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.1ms
video 1/1 (212/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.5ms
video 1/1 (213/516) /content/IMG_5357.mov: 640x384 (no detections), 363.9ms
video 1/1 (214/516) /content/IMG_5357.mov: 640x384 (no detections), 349.7ms
video 1/1 (215/516) /content/IMG_5357.mov: 640x384 (no detections), 350.6ms
video 1/1 (216/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.7ms
video 1/1 (217/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.8ms
video 1/1 (218/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.6ms
video 1/1 (219/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.3ms
video 1/1 (220/516) /content/IMG_5357.mov: 640x384 1 ladybug, 339.6ms
video 1/1 (221/516) /content/IMG_5357.mov: 640x384 1 ladybug, 553.8ms
video 1/1 (222/516) /content/IMG_5357.mov: 640x384 1 ladybug, 570.4ms
video 1/1 (223/516) /content/IMG_5357.mov: 640x384 1 ladybug, 575.2ms
video 1/1 (224/516) /content/IMG_5357.mov: 640x384 1 ladybug, 580.4ms
video 1/1 (225/516) /content/IMG_5357.mov: 640x384 1 ladybug, 566.4ms
video 1/1 (226/516) /content/IMG_5357.mov: 640x384 1 ladybug, 554.1ms
video 1/1 (227/516) /content/IMG_5357.mov: 640x384 1 ladybug, 506.9ms
video 1/1 (228/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.2ms
video 1/1 (229/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.4ms
video 1/1 (230/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.3ms
video 1/1 (231/516) /content/IMG_5357.mov: 640x384 1 ladybug, 342.0ms
video 1/1 (232/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.7ms
video 1/1 (233/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.4ms
video 1/1 (234/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.6ms
video 1/1 (235/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.3ms
video 1/1 (236/516) /content/IMG_5357.mov: 640x384 1 ladybug, 347.2ms
video 1/1 (237/516) /content/IMG_5357.mov: 640x384 1 ladybug, 368.2ms
video 1/1 (238/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.3ms
video 1/1 (239/516) /content/IMG_5357.mov: 640x384 1 ladybug, 352.3ms
video 1/1 (240/516) /content/IMG_5357.mov: 640x384 1 ladybug, 360.1ms
video 1/1 (241/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.4ms
video 1/1 (242/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.5ms
video 1/1 (243/516) /content/IMG_5357.mov: 640x384 1 ladybug, 342.3ms
video 1/1 (244/516) /content/IMG_5357.mov: 640x384 1 ladybug, 350.3ms
video 1/1 (245/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.8ms
video 1/1 (246/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.4ms
video 1/1 (247/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.4ms
video 1/1 (248/516) /content/IMG_5357.mov: 640x384 1 ladybug, 359.3ms
video 1/1 (249/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.8ms
video 1/1 (250/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.3ms
video 1/1 (251/516) /content/IMG_5357.mov: 640x384 1 ladybug, 362.6ms
video 1/1 (252/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.6ms
video 1/1 (253/516) /content/IMG_5357.mov: 640x384 1 ladybug, 345.5ms
video 1/1 (254/516) /content/IMG_5357.mov: 640x384 1 ladybug, 358.1ms
video 1/1 (255/516) /content/IMG_5357.mov: 640x384 1 ladybug, 512.8ms
video 1/1 (256/516) /content/IMG_5357.mov: 640x384 1 ladybug, 561.8ms
video 1/1 (257/516) /content/IMG_5357.mov: 640x384 1 ladybug, 568.6ms
video 1/1 (258/516) /content/IMG_5357.mov: 640x384 1 ladybug, 571.3ms
video 1/1 (259/516) /content/IMG_5357.mov: 640x384 1 ladybug, 567.9ms
video 1/1 (260/516) /content/IMG_5357.mov: 640x384 1 ladybug, 554.0ms
video 1/1 (261/516) /content/IMG_5357.mov: 640x384 1 ladybug, 544.9ms
video 1/1 (262/516) /content/IMG_5357.mov: 640x384 1 ladybug, 368.5ms
video 1/1 (263/516) /content/IMG_5357.mov: 640x384 1 ladybug, 354.6ms
video 1/1 (264/516) /content/IMG_5357.mov: 640x384 1 ladybug, 372.7ms
video 1/1 (265/516) /content/IMG_5357.mov: 640x384 1 ladybug, 355.4ms
video 1/1 (266/516) /content/IMG_5357.mov: 640x384 1 ladybug, 353.6ms
video 1/1 (267/516) /content/IMG_5357.mov: 640x384 1 ladybug, 357.7ms
video 1/1 (268/516) /content/IMG_5357.mov: 640x384 1 ladybug, 341.3ms
video 1/1 (269/516) /content/IMG_5357.mov: 640x384 1 ladybug, 349.4ms
video 1/1 (270/516) /content/IMG_5357.mov: 640x384 1 ladybug, 346.2ms
video 1/1 (271/516) /content/IMG_5357.mov: 640x384 1 ladybug, 343.3ms
video 1/1 (272/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.3ms
video 1/1 (273/516) /content/IMG_5357.mov: 640x384 1 ladybug, 348.8ms
video 1/1 (274/516) /content/IMG_5357.mov: 640x384 1 ladybug, 356.6ms

In [207]:
result = results[0]
box = result.boxes
face_count = len(box)

In [208]:
print(face_count)

1

In [209]:
for box in result.boxes:
      class_id = result.names[box.cls[0].item()]
      conf = round(box.conf[0].item(), 2)
      print("Type:", class_id, conf)

Type: ladybug 0.75

In [210]:
print(box.conf[0].item())

0.750643789768219

In [211]:
import pandas as pd
import numpy as np
import datetime

df = pd.DataFrame(columns = ['Species', 'Confiance', 'id_video', 'Time'])

for j in results:
  result = j
  box = result.boxes
  for box in result.boxes:
      class_id = result.names[box.cls[0].item()]
      conf = round(box.conf[0].item(), 2)
      conf = float(conf)
      id = box.id
      if id == None:
        id = 0
      else:
        id = id
      if id == 0:
        id = 0
      else:
        id = int(id.item())
      print("Type:", class_id, conf, id)
      time = datetime.datetime.today()
      date_formatee = time.strftime("%d/%m/%Y %H:%M")
      df.loc[j] = [class_id, conf, id, date_formatee]

Type: ladybug 0.75 1
Type: ladybug 0.76 1
Type: ladybug 0.75 1
Type: ladybug 0.79 1
Type: ladybug 0.77 1
Type: ladybug 0.74 1
Type: ladybug 0.76 1
Type: ladybug 0.77 1
Type: ladybug 0.72 1
Type: ladybug 0.79 1
Type: ladybug 0.76 1
Type: ladybug 0.75 1
Type: ladybug 0.8 1
Type: ladybug 0.79 1
Type: ladybug 0.8 1
Type: ladybug 0.8 1
Type: ladybug 0.79 1
Type: ladybug 0.77 1
Type: ladybug 0.74 1
Type: ladybug 0.74 1
Type: ladybug 0.75 1
Type: ladybug 0.73 0
Type: ladybug 0.76 0
Type: ladybug 0.77 3
Type: ladybug 0.79 3
Type: ladybug 0.77 3
Type: ladybug 0.75 3
Type: ladybug 0.81 3
Type: ladybug 0.8 3
Type: ladybug 0.75 3
Type: ladybug 0.77 3
Type: ladybug 0.78 3
Type: ladybug 0.73 3
Type: ladybug 0.79 3
Type: ladybug 0.73 3
Type: ladybug 0.8 3
Type: ladybug 0.8 3
Type: ladybug 0.73 3
Type: ladybug 0.77 3
Type: ladybug 0.74 3
Type: ladybug 0.78 3
Type: ladybug 0.73 3
Type: ladybug 0.8 3
Type: ladybug 0.78 3
Type: ladybug 0.77 3
Type: ladybug 0.78 3
Type: ladybug 0.76 3
Type: ladybug 0.77 3
Type: ladybug 0.74 3
Type: ladybug 0.75 3
Type: ladybug 0.77 3
Type: ladybug 0.77 3
Type: ladybug 0.75 3
Type: ladybug 0.79 3
Type: ladybug 0.78 3
Type: ladybug 0.79 3
Type: ladybug 0.76 3
Type: ladybug 0.76 3
Type: ladybug 0.75 3
Type: ladybug 0.74 3
Type: ladybug 0.71 3
Type: ladybug 0.78 3
Type: ladybug 0.75 3
Type: ladybug 0.78 3
Type: ladybug 0.69 3
Type: ladybug 0.75 3
Type: ladybug 0.73 3
Type: ladybug 0.75 0
Type: ladybug 0.78 0
Type: ladybug 0.71 0
Type: ladybug 0.73 6
Type: ladybug 0.62 6
Type: ladybug 0.78 6
Type: ladybug 0.7 6
Type: ladybug 0.79 6
Type: ladybug 0.79 6
Type: ladybug 0.73 6
Type: ladybug 0.81 6
Type: ladybug 0.79 6
Type: ladybug 0.78 6
Type: ladybug 0.73 6
Type: ladybug 0.69 6
Type: ladybug 0.78 6
Type: ladybug 0.68 6
Type: ladybug 0.71 6
Type: ladybug 0.76 6
Type: ladybug 0.76 6
Type: ladybug 0.8 6
Type: ladybug 0.75 0
Type: ladybug 0.75 0
Type: ladybug 0.72 0
Type: ladybug 0.7 0
Type: ladybug 0.78 0
Type: ladybug 0.78 11
Type: ladybug 0.59 11
Type: ladybug 0.66 11
Type: ladybug 0.73 11
Type: ladybug 0.76 11
Type: ladybug 0.78 11
Type: ladybug 0.73 11
Type: ladybug 0.7 11
Type: ladybug 0.75 11
Type: ladybug 0.67 11
Type: ladybug 0.7 11
Type: ladybug 0.79 11
Type: ladybug 0.78 11
Type: ladybug 0.74 11
Type: ladybug 0.72 11
Type: ladybug 0.67 11
Type: ladybug 0.67 11
Type: ladybug 0.66 0
Type: ladybug 0.54 0
Type: ladybug 0.74 0
Type: ladybug 0.78 0
Type: ladybug 0.7 14
Type: ladybug 0.72 14
Type: ladybug 0.74 14
Type: ladybug 0.75 14
Type: ladybug 0.81 14
Type: ladybug 0.66 14
Type: ladybug 0.71 14
Type: ladybug 0.81 14
Type: ladybug 0.83 14
Type: ladybug 0.69 14
Type: ladybug 0.76 14
Type: ladybug 0.84 14
Type: ladybug 0.82 14
Type: ladybug 0.82 14
Type: ladybug 0.78 14
Type: ladybug 0.72 14
Type: ladybug 0.71 14
Type: ladybug 0.75 14
Type: ladybug 0.79 14
Type: ladybug 0.71 14
Type: ladybug 0.69 14
Type: ladybug 0.82 14
Type: ladybug 0.8 14
Type: ladybug 0.81 14
Type: ladybug 0.81 14
Type: ladybug 0.76 14
Type: ladybug 0.65 14
Type: ladybug 0.74 0
Type: ladybug 0.58 0
Type: ladybug 0.59 0
Type: ladybug 0.66 0
Type: ladybug 0.52 0
Type: ladybug 0.67 0
Type: ladybug 0.54 0
Type: ladybug 0.7 0
Type: ladybug 0.77 18
Type: ladybug 0.58 18
Type: ladybug 0.6 0
Type: ladybug 0.73 18
Type: ladybug 0.66 0
Type: ladybug 0.78 0
Type: ladybug 0.55 0
Type: ladybug 0.65 0
Type: ladybug 0.64 0
Type: ladybug 0.63 0
Type: ladybug 0.78 0
Type: ladybug 0.73 0
Type: ladybug 0.75 26
Type: ladybug 0.77 26
Type: ladybug 0.73 26
Type: ladybug 0.83 26
Type: ladybug 0.77 26
Type: ladybug 0.8 26
Type: ladybug 0.78 26
Type: ladybug 0.67 0
Type: ladybug 0.55 27
Type: ladybug 0.74 27
Type: ladybug 0.76 27
Type: ladybug 0.65 27
Type: ladybug 0.72 27
Type: ladybug 0.81 27
Type: ladybug 0.65 27
Type: ladybug 0.62 27
Type: ladybug 0.65 27
Type: ladybug 0.66 27
Type: ladybug 0.76 27
Type: ladybug 0.73 27
Type: ladybug 0.72 27
Type: ladybug 0.76 27
Type: ladybug 0.81 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.8 27
Type: ladybug 0.75 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27
Type: ladybug 0.77 27
Type: ladybug 0.75 27
Type: ladybug 0.8 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.71 27
Type: ladybug 0.76 27
Type: ladybug 0.75 27
Type: ladybug 0.77 27
Type: ladybug 0.8 27
Type: ladybug 0.78 27
Type: ladybug 0.73 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.76 27
Type: ladybug 0.79 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.78 27
Type: ladybug 0.8 27
Type: ladybug 0.83 27
Type: ladybug 0.82 27
Type: ladybug 0.79 27
Type: ladybug 0.8 27
Type: ladybug 0.83 27
Type: ladybug 0.77 27
Type: ladybug 0.82 27
Type: ladybug 0.83 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.79 27
Type: ladybug 0.79 27
Type: ladybug 0.79 27
Type: ladybug 0.82 27
Type: ladybug 0.8 27
Type: ladybug 0.82 27
Type: ladybug 0.85 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.83 27
Type: ladybug 0.82 27
Type: ladybug 0.84 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.81 27
Type: ladybug 0.79 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.81 27
Type: ladybug 0.81 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.83 27
Type: ladybug 0.83 27
Type: ladybug 0.82 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.81 27
Type: ladybug 0.8 27
Type: ladybug 0.79 27
Type: ladybug 0.83 27
Type: ladybug 0.81 27
Type: ladybug 0.82 27
Type: ladybug 0.83 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.82 27
Type: ladybug 0.81 27
Type: ladybug 0.8 27
Type: ladybug 0.82 27
Type: ladybug 0.79 27
Type: ladybug 0.76 27
Type: ladybug 0.78 27
Type: ladybug 0.79 27
Type: ladybug 0.8 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.74 27
Type: ladybug 0.75 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.79 27
Type: ladybug 0.8 27
Type: ladybug 0.81 27
Type: ladybug 0.74 27
Type: ladybug 0.76 27
Type: ladybug 0.79 27
Type: ladybug 0.79 27
Type: ladybug 0.79 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.69 27
Type: ladybug 0.78 27
Type: ladybug 0.73 27
Type: ladybug 0.7 27
Type: ladybug 0.72 27
Type: ladybug 0.7 27
Type: ladybug 0.72 27
Type: ladybug 0.79 27
Type: ladybug 0.73 27
Type: ladybug 0.74 27
Type: ladybug 0.73 27
Type: ladybug 0.8 27
Type: ladybug 0.78 27
Type: ladybug 0.71 27
Type: ladybug 0.75 27
Type: ladybug 0.7 27
Type: ladybug 0.78 27
Type: ladybug 0.72 27
Type: ladybug 0.71 27
Type: ladybug 0.76 27
Type: ladybug 0.72 27
Type: ladybug 0.57 27
Type: ladybug 0.66 27
Type: ladybug 0.74 27
Type: ladybug 0.73 27
Type: ladybug 0.79 27
Type: ladybug 0.74 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.73 27
Type: ladybug 0.77 27
Type: ladybug 0.8 27
Type: ladybug 0.7 27
Type: ladybug 0.71 27
Type: ladybug 0.69 27
Type: ladybug 0.7 27
Type: ladybug 0.71 27
Type: ladybug 0.7 27
Type: ladybug 0.74 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27
Type: ladybug 0.74 27
Type: ladybug 0.74 27
Type: ladybug 0.77 27
Type: ladybug 0.72 27
Type: ladybug 0.73 27
Type: ladybug 0.79 27
Type: ladybug 0.75 27
Type: ladybug 0.73 27
Type: ladybug 0.74 27
Type: ladybug 0.74 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.74 27
Type: ladybug 0.7 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.75 27
Type: ladybug 0.75 27
Type: ladybug 0.76 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.74 27
Type: ladybug 0.73 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.79 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.8 27
Type: ladybug 0.79 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.75 27
Type: ladybug 0.77 27
Type: ladybug 0.79 27
Type: ladybug 0.8 27
Type: ladybug 0.74 27
Type: ladybug 0.77 27
Type: ladybug 0.74 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.79 27
Type: ladybug 0.78 27
Type: ladybug 0.79 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.79 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.74 27
Type: ladybug 0.75 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27
Type: ladybug 0.79 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.75 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.79 27
Type: ladybug 0.8 27
Type: ladybug 0.81 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.75 27
Type: ladybug 0.76 27
Type: ladybug 0.74 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.75 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.75 27
Type: ladybug 0.76 27
Type: ladybug 0.75 27
Type: ladybug 0.73 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.76 27
Type: ladybug 0.77 27
Type: ladybug 0.76 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.78 27
Type: ladybug 0.77 27
Type: ladybug 0.8 27
Type: ladybug 0.8 27

In [212]:
df = df.reset_index()

In [213]:
df = df.drop(['index'], axis = 1)

In [214]:
df

     Species  Confiance  id_video              Time
0    ladybug       0.75         1  30/06/2023 11:50
1    ladybug       0.76         1  30/06/2023 11:50
2    ladybug       0.75         1  30/06/2023 11:50
3    ladybug       0.79         1  30/06/2023 11:50
4    ladybug       0.77         1  30/06/2023 11:50
..       ...        ...       ...               ...
464  ladybug       0.78        27  30/06/2023 11:50
465  ladybug       0.78        27  30/06/2023 11:50
466  ladybug       0.77        27  30/06/2023 11:50
467  ladybug       0.80        27  30/06/2023 11:50
468  ladybug       0.80        27  30/06/2023 11:50

[469 rows x 4 columns]

In [215]:
df2 = df.drop(df[df['id_video'] == 0].index, inplace = False)

In [216]:
df2

     Species  Confiance  id_video              Time
0    ladybug       0.75         1  30/06/2023 11:50
1    ladybug       0.76         1  30/06/2023 11:50
2    ladybug       0.75         1  30/06/2023 11:50
3    ladybug       0.79         1  30/06/2023 11:50
4    ladybug       0.77         1  30/06/2023 11:50
..       ...        ...       ...               ...
464  ladybug       0.78        27  30/06/2023 11:50
465  ladybug       0.78        27  30/06/2023 11:50
466  ladybug       0.77        27  30/06/2023 11:50
467  ladybug       0.80        27  30/06/2023 11:50
468  ladybug       0.80        27  30/06/2023 11:50

[437 rows x 4 columns]

In [217]:
df3 = df2.groupby(['id_video','Species','Time'], as_index=False).mean('Confiance')
df3

   id_video  Species              Time  Confiance
0         1  ladybug  30/06/2023 11:50   0.766190
1         3  ladybug  30/06/2023 11:50   0.763409
2         6  ladybug  30/06/2023 11:50   0.746111
3        11  ladybug  30/06/2023 11:50   0.718824
4        14  ladybug  30/06/2023 11:50   0.757778
5        18  ladybug  30/06/2023 11:50   0.693333
6        26  ladybug  30/06/2023 11:50   0.775714
7        27  ladybug  30/06/2023 11:50   0.769967

In [218]:
data = [['ladybug', 'coleopteres'], ['bee', 'pollinisateur'], ['butterfly', 'pollinisateur']]

df_data = pd.DataFrame(data, columns =['Species', 'Category'])

In [219]:
df_test = df3.merge(df_data, how='inner', on='Species')
df_test

   id_video  Species              Time  Confiance     Category
0         1  ladybug  30/06/2023 11:50   0.766190  coleopteres
1         3  ladybug  30/06/2023 11:50   0.763409  coleopteres
2         6  ladybug  30/06/2023 11:50   0.746111  coleopteres
3        11  ladybug  30/06/2023 11:50   0.718824  coleopteres
4        14  ladybug  30/06/2023 11:50   0.757778  coleopteres
5        18  ladybug  30/06/2023 11:50   0.693333  coleopteres
6        26  ladybug  30/06/2023 11:50   0.775714  coleopteres
7        27  ladybug  30/06/2023 11:50   0.769967  coleopteres

In [220]:
df_final = df_test[['Species','Category','Time']]
df_final

   Species     Category              Time
0  ladybug  coleopteres  30/06/2023 11:50
1  ladybug  coleopteres  30/06/2023 11:50
2  ladybug  coleopteres  30/06/2023 11:50
3  ladybug  coleopteres  30/06/2023 11:50
4  ladybug  coleopteres  30/06/2023 11:50
5  ladybug  coleopteres  30/06/2023 11:50
6  ladybug  coleopteres  30/06/2023 11:50
7  ladybug  coleopteres  30/06/2023 11:50

In [221]:
df_final.to_csv('csv_final.csv',index=False, sep=';')